kind: Service
apiVersion: v1
metadata:
  name: windows-metrics
  namespace: openshift-windows
  labels:
    k8s-app: windows-metrics
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9182
      protocol: TCP
      targetPort: 9182
