apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: windows-metrics-sm
  namespace: openshift-windows
  labels:
    k8s-app: windows-metrics
    prometheus: prometheus-k8s
    app.kubernetes.io/name: windows-exporter
spec:
  selector:
    matchLabels:
      k8s-app: windows-metrics
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
      path: "/metrics"
      relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_endpoint_address_target_name
        targetLabel: instance
